services:
  qdrant:
    # https://hub.docker.com/r/qdrant/qdrant/tags
    image: qdrant/qdrant:latest
    restart: unless-stopped
    volumes:
      - /data/qdrant:/qdrant/storage
      - ./qdrant_config.yml:/qdrant/config/production.yaml
    environment:
      - QDRANT_ALLOW_RECOVERY_MODE=true
      # - VIRTUAL_HOST=qdrant.137.120.31.148.nip.io
      # - LETSENCRYPT_HOST=qdrant.137.120.31.148.nip.io
      # - VIRTUAL_PORT=6333
    ports:
      - 6333:6333
      - 6334:6334

    # command:
    #   - ./qdrant --config-path /qdrant/qdrant_config.yml
